### ISSUE TITLE
Parse JSON-LD into C# object

### ISSUE THREAD

**Issue by chriszirkel** [RehanSaeed/Schema.NET#3] opened 2017-08-30 13:50 UTC
Hi,

is it possible to parse JSON-LD data into a C# object. According to the documentation, it seems that the conversion is only the other way around from a C# object to JSON-LD data.

**Comment by RehanSaeed** [comment] 2017-08-30 14:20
Duplicate of https://github.com/RehanSaeed/Schema.NET/issues/2

**Closed by RehanSaeed** 2017-08-30 14:20 UTC
